### PR TITLE
changed all fromstring() to frombuffer() due to deprecation warnings in numpy 

### PR DESCRIPTION
**Pull request by goharkay**
changed all fromstring() to frombuffer() due to deprecation warnings in numpy

### CODE REVIEW

**Comment by scollis** [comment]
Thanks @goharkay We will review!

**Comment by scollis** [comment]
This is a fix for nexrad.. it is also in the UF reader, MDV reader and a few others..

**Comment by scollis** [comment]
@goharkay we are going to merge #702 before this

**Comment by scollis** [comment]
I'm going to close and open this to force unit tests to run again

**Comment by scollis** [comment]
ok.. Appveyor is happy... 
The fail in Travis is becuase the 2.7 build could not download cartopy etc.. A resolve error..
 ```

The command "eval xvfb-run nosetests $NOSE_ARGS" exited with 0.
after_success.1
0.00s$ if [[ "$COVERALLS" == "true" ]]; then coveralls || echo "failed"; fi
$ if [[ "$DOC_BUILD" == "true" ]]; then cd $TRAVIS_BUILD_DIR; source continuous_integration/build_docs.sh; fi
Building Docs
Solving environment: ...working... failed
UnsatisfiableError: The following specifications were found to be in conflict:
  - cartopy
  - geotiff
  - pil
Use "conda info <package>" to see the dependencies for each package.

```
@zssherman this might be something we need to do a fix for..

Merging

**Comment by zssherman** [comment]
@scollis Odd yeah I don't think those packages ever caused an issue before. I can investigate.

**Pull request merged**
