### PR TITLE
ADD: Velocity Azimuth Display

### PR DESCRIPTION
**Pull request by zssherman**
Hi Jonathan,

Here is the PR that contains the vad code for review,

Code adapted by Scott Collis or as stated,
"Below is some code from Susan Rennie (based off Michelson et al 2000) from the Centre for Australian Weather and Climate Research (CAWCR) for calculating VADs. I used her one tilt version and wrote my own adaptation into Py-ART PyRadar object.. Note I convert to U and V before averaging.. my concern is that if you have θ rapidly varying between 360° and 0° this will average to a nonsense number" (Collis).

Michelson, D. B., Andersson, T., Koistinen, J., Collier, C. G., Riedl, J.,
Szturc, J., Gjertsen, U., Nielsen, A. and Overgaard, S. (2000) BALTEX Radar
Data Centre Products and their Methodologies. In SMHI Reports. Meteorology
and Climatology. Swedish Meteorological and Hydrological Institute, Norrkoping.

@jjhelmus I also added some comments regarding the singleton-comparison we discussed.

### CODE REVIEW

**Comment by scollis** [comment]
Good stuff @zssherman  I was just discussing this with @tjlang yesterday.

**Comment by zssherman** [comment]
@scollis Hopefully I did this correctly, just wish the checks didn't fail.

**Comment by jjhelmus** [comment]
@zssherman I created a quick test of the VAD routine to try to retrieve a horizontal profile with a fixed wind speed and direction.  From this it looks like the two wind components are reversed.  Also a lot of NaNs are leaking into the results.  Can you look into these error?

``` Python
from __future__ import print_function
import matplotlib.pyplot as plt
import numpy as np
import pyart

# create a profile of 100 heights up to 500 m with 5 m/s winds at 25 degrees
height = np.linspace(0, 500, 100)
speed = np.ones_like(height) * 5
direction = np.ones_like(height) * 25
profile = pyart.core.HorizontalWindProfile(height, speed, direction)


# simulate a single sweep radar with a velocity field from the profile
test_radar = pyart.testing.make_target_radar()
test_radar.elevation['data'][:] = 45.0
test_radar.fixed_angle['data'][:] = 45.0
print("max height:", test_radar.gate_z['data'].max())
sim_vel = pyart.util.simulated_vel_from_profile(test_radar, profile)
test_radar.add_field('velocity', sim_vel, replace_existing=True)

# perform a VAD retrieval
vad = pyart.retrieve.velocity_azimuth_display(
    test_radar, 'velocity', 0, 500, 100)

# plot the original winds and the retrieved winds
fig = plt.figure()
ax = fig.add_subplot(111)

ax.plot(profile.u_wind, profile.height, 'r-')
ax.plot(profile.v_wind, profile.height, 'b-')

ax.plot(vad.u_wind, vad.height, 'g--')
ax.plot(vad.v_wind, vad.height, 'k--')

ax.set_xlim(-5, 0)
plt.show()

# print out the results
print("Height")
print(profile.height[:5])
print(vad.height[:5])
print(profile.height[-5:])
print(vad.height[-5:])

print("u_wind:")
print(profile.u_wind[:5])
print(vad.u_wind[:5])
print(profile.u_wind[-5:])
print(vad.u_wind[-5:])

print("v_wind:")
print(profile.v_wind[:5])
print(vad.v_wind[:5])
print(profile.v_wind[-5:])
print(vad.v_wind[-5:])

print("speed:")
print(profile.speed[:5])
print(vad.speed[:5])

print("direction:")
print(profile.direction[:5])
print(vad.direction[:5])
```

Results:

```
Height
[  0.           5.05050505  10.1010101   15.15151515  20.2020202 ]
[  0.           5.05050505  10.1010101   15.15151515  20.2020202 ]
[ 479.7979798   484.84848485  489.8989899   494.94949495  500.        ]
[ 479.7979798   484.84848485  489.8989899   494.94949495  500.        ]
u_wind:
[-2.11309131 -2.11309131 -2.11309131 -2.11309131 -2.11309131]
[        nan -4.53125818         nan         nan -4.53125818]
[-2.11309131 -2.11309131 -2.11309131 -2.11309131 -2.11309131]
[      nan -0.015884       nan       nan -0.015884]
v_wind:
[-4.53153894 -4.53153894 -4.53153894 -4.53153894 -4.53153894]
[        nan -2.11309867         nan         nan -2.11309867]
[-4.53153894 -4.53153894 -4.53153894 -4.53153894 -4.53153894]
[        nan  0.00041593         nan         nan  0.00041593]
speed:
[ 5.  5.  5.  5.  5.]
[        nan  4.99974866         nan         nan  4.99974866]
direction:
[ 25.  25.  25.  25.  25.]
[         nan  64.99856383          nan          nan  64.99856383]
```

**Comment by zssherman** [comment]
@jjhelmus Gotcha, i'll take a look right away.

**Comment by Rumpkie** [comment]
@zssherman I was looking through this PR today, I believe the failure of your code to pass the CI tests for 3.5 and 3.6 is that when you divide the number of nrays/2 it returns a float, it needs to use the floor division operator // for an int result. nrays//2.. Give it a shot see what happens.

**Comment by zssherman** [comment]
@rumpkie Ah gotcha that makes sense, i'll give it a shot. I was alsp able to figure out whu the values wete flipped between u and v mean. Jonathan gave me some of his VAD code to replace the code in the pull request that was put on hold for the beam block. Depending on what you and Scott think is best I can continue and fix this code, use Jonathan's VAD code or both.

**Pull request closed without merging**
