### PR TITLE
MAINT: Reverted init back to original state, minus having nose.

### PR DESCRIPTION
**Pull request by zssherman**

### CODE REVIEW

**Comment by scollis** [comment]
Good to go? @zssherman ?

**Comment by scollis** [comment]
Actually I am going to have @jhemedin check this.. @jhemedin please grab this branch (from @zssherman ) and test

**Comment by scollis** [comment]
@zssherman can help you

**Comment by jhemedin** [comment]
@scollis good to go, had no errors while testing.

**Comment by scollis** [comment]
Thank you all. Merging

**Pull request merged**
