### PR TITLE
ADD: Meteoswiss differential attenuation code

### PR DESCRIPTION
**Pull request by rcjackson**
This adds in the differential attenuation code made by @jfigui and others from the meteoswiss fork of Py-ART. In addition, modules that the differential attenuation code depends on were also added.

### CODE REVIEW

**Comment by scollis** [comment]
ping @meteoswiss-mdr

**Comment by scollis** [comment]
Tests are failing..
``` def test_attenuation():
        spec_at, cor_z = perform_attenuation()
        ref = np.load(REFERENCE_RAYS_FILE)
>       assert_allclose(ref['spec_at'], spec_at['data'])
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0
E       
E       (mismatch 98.47405900305188%)
E        x: array([5.368297e-04, 2.894919e-04, 2.264874e-04, 4.842263e-04,
E              5.477306e-04, 2.428047e-04, 9.636534e-05, 8.557841e-05,
E              1.516762e-04, 1.687329e-04, 9.185078e-05, 4.364006e-05,...
E        y: array([5.368277e-04, 2.894909e-04, 2.264865e-04, 4.842245e-04,
E              8.411111e-04, 8.723008e-04, 3.434653e-04, 1.303811e-04,
E              1.516837e-04, 1.687413e-04, 9.185536e-05, 4.364223e-05,...
../../../../miniconda3/envs/testenv/lib/python3.6/site-packages/pyart/correct/tests/test_attenuation.py:22: AssertionError
________________________ test_specific_diff_attenuation ________________________```

**Comment by scollis** [comment]
This could be due to different precision on cloud host than your machine.. suggest relaxing precision.

**Comment by rcjackson** [comment]
Yeah, there is just a slight difference as I had to regenerate the example ray file to include ZDR which probably now has slightly different data just due to differences in rounding. I set the absolute tolerance to 0.001 dB/km...anything smaller than that is probably questionable anyways.

**Comment by rcjackson** [comment]
Looks like some GDAL issue with py2.7.

**Comment by scollis** [comment]
Yep.. I am following up https://github.com/OSGeo/gdal/issues/1120

**Comment by scollis** [comment]
I am accepting this PR. GDAL issue is not related to this.

**Comment by meteoswiss-mdr** [comment]
Wonderful! Thanks a lot!

**Comment by kmuehlbauer** [comment]
@scollis @rcjackson The travis-log indicates that all packages come from `defaults` channel. This happens in the step to install `pytest-cov` [here](https://github.com/ARM-DOE/pyart/blob/b0360a8fef5e73499249c97ee1c2b0dc2ccc9147/continuous_integration/install.sh#L26). This might be the main reason why this is failing.

**Comment by zssherman** [comment]
@kmuehlbauer Thanks for the suggestion! I'll put in a pull request and see if it fixes it.

**Pull request merged**
