### PR TITLE
ADD: Add DoE acknowledgement to __init__.py

### PR DESCRIPTION
**Pull request by scollis**
Adds an Acknowledgement request for users. This acknowledgement will allow DoE to track usage in publications.

### CODE REVIEW

**Comment by scollis** [comment]
No idea why CI is failing.. could you take a look @jjhelmus

**Comment by jjhelmus** [comment]
Closing and re-opening PR to re-trigger CI.

**Comment by swnesbitt** [comment]
Can we do a poll to see whether the users want this ;)

**Comment by scollis** [comment]
It can be disabled @swnesbitt :) We are required to add this or something like it as ARM funds some of @jjhelmus , @Rumpkie  and my time..

**Comment by jjhelmus** [comment]
Can this text be a bit less verbose?  I do not like the idea of printing so much text (13 lines vs. the current 6) every time users import Py-ART.  I'm not a big fan of printing anything at but I am keenly aware of the need for reference and proper citatations.

**Comment by scollis** [comment]
@jjhelmus I will check with ARM management.

**Comment by swnesbitt** [comment]
Could it just be one line, with a URL to the required acknowledgements?

**Comment by jjhelmus** [comment]
As an alternative could this text be added to the README file and a blurb added to the import text suggesting users refer there for more citation/Acknowledgements/funding?

**Comment by jjhelmus** [comment]
The format and length of the current text was adapted from the examples provided by C. Titus Brown in his [blog post of the topic](http://ivory.idyll.org/blog/2014-citations.html).

The message can be disabled by setting the `PYART_QUIET` environment variable.  I include the line `export PYART_QUIET=""` in my .bashrc to accomplish this.

**Comment by scollis** [comment]
I have emailed management.. I like the idea of just pointing to a URL. Again, we need to take care, in a time of flat funding and diminishing resources it is vital to acknowledge the generous support of ARM and ARM's bread and butter is acknowledgements in papers.

**Comment by scollis** [comment]
Ok.. Talked to Jim.. How about:
`
## You are using the Python ARM Radar Toolkit (Py-ART), an open source
## library for working with weather radar data which is partly supported by 
## the U.S. Department of Energy as part of the Atmospheric Radiation 
## Measurement (ARM) Climate Research Facility, an Office of Science user 
## facility.
## If you use this software to prepare a publication, please cite:
##
##     JJ Helmus and SM Collis, JORS 2016, doi: 10.5334/jors.119 
`

**Comment by jjhelmus** [comment]
I'm happy with the suggested text.  Wrap it at 74 character and add a blank line after the first paragraph, and split the long sentence and I'd be happier still.  

For example:

```
## You are using the Python ARM Radar Toolkit (Py-ART), an open source
## library for working with weather radar data. Py-ART is partly
## supported by the U.S. Department of Energy as part of the Atmospheric
## Radiation Measurement (ARM) Climate Research Facility, an Office of
## Science user facility.
##
## If you use this software to prepare a publication, please cite:
##
##     JJ Helmus and SM Collis, JORS 2016, doi: 10.5334/jors.119 
```

**Comment by scollis** [comment]
Just pushed this change.. Please review @jjhelmus We need this before Sunday

**Comment by jjhelmus** [comment]
LGMT.  The CI fails are due to some dependencies and kludges in the environment setup that will need to be fixed at some later time.

**Pull request merged**
