### PR TITLE
Latlon for points in grid

### PR DESCRIPTION
**Pull request by gamaanderson**
add a function to create in grid object from the axes x_disp,y_disp,lat and lon, 2-d axes for the latitude or longitude of every point the the xy plane. The math is "simple" azimuthal equidistant projetion to latlon. I map it into pyart so I can call as a user, but one should decide how to implement, if as method in grid or something else

### CODE REVIEW

**Comment by kirknorth** [comment]
I think the most generic approach here would be to utilize the `pyproj` package to compute the locations of each (x, y) point in a `Grid`. The idea here is that the user would be able to more accurately compute these locations  anywhere on the Earth through the ability to change the `proj` kwarg for the map projection, and to a lesser extent the `datum` and `ellps` kwargs. Just my two cents.

**Comment by gamaanderson** [comment]
That a good idea @kirknorth , this however will create a new dependency (or is it already in use some else?), but if not one has a problem with that I will be implementing it.  I wounder if Grid should have a internal proj or more extensive projection description, but that is not for me to decide, I'm just using kwarg as you suggested.

**Comment by kirknorth** [comment]
@gamaanderson yes it's implicitly required to use any of the map display routines (e.g. `GridMapDisplay`). I say implicit because `pyproj` is available from `basemap`.

**Comment by scollis** [comment]
Yep.. We can call pyproj from Matplotlib..

However Matplotlib is an optional dependancy.  So I suggest we build on 
Anderson's PR with a check for matplotlib.. if matplotlib exists it 
should call pyproj.. if not it can use the simple but effective 
technique he has proposed.

Great discussion all.


On 4/1/15 6:32 PM, Kirk North wrote:
>
> @gamaanderson <https://github.com/gamaanderson> yes it's implicitly 
> required to use any of the map display routines (e.g. 
> |GridMapDisplay|). I say implicit because |pyproj| is available from 
> |basemap|.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ARM-DOE/pyart/pull/264#issuecomment-88663465>.
>

-- 
I ride for Parkinsons research http://www.events.org/sponsorship.aspx?id=51573

**Comment by gamaanderson** [comment]
I try to implement Basemap, but my version (Debian wheezy) seem to have a bug. Please some one try the following:

from mpl_toolkits.basemap import Basemap
b = Basemap(lat_0=0,lon_0=0,projection='aeqd')
b(2.5e+5, 2.5e+5, inverse=True)

This should return (2.24, 2.24). Mine return (1e+30, 1e+30)!

Anyway I let Basemap version commented and put pyproj version instead
Error from the internal implementation is around 10e-3, probably because of earth radius

**Comment by tjlang** [comment]
I get 1e+30 too. Ananconda on Mac and Linux.

Timothy Lang

**Comment by kirknorth** [comment]
@gamaanderson when I do

```python
from mpl_toolkits.basemap import pyproj

pj = pyproj.Proj(lat_0=0.0, lon_0=0.0, proj='aeqd')
print pj(2.5e5, 2.5e5, inverse=True) -> (2.24694..., 2.26033...)
```

**Comment by gamaanderson** [comment]
In fact it does, i didn't realize that , but documentation indicates Basemap should work just as good.

Anyway, should I just import pyproj from mpl_toolkits.basemap and put Basemap to rest?

**Comment by kirknorth** [comment]
This is what we already do in **gridmapdisplay.py** so I wouldn't worry about being inconsistent or anything of that sort.

**Comment by gamaanderson** [comment]
Done and tested! Thank you for the help @kirknorth

**Comment by jjhelmus** [comment]
In the future this functionality should be added as a method to the **Grid** method, but this can wait for the refactoring of the class as discusses in #285.  At the same time the metadata of the latitude and longitude dictionaries should moved to the `default_config.py` file.  

There are a few style issues that I will fix post-merge.

**Pull request merged**
