### PR TITLE
ADD: new GridMapDisplay class that uses Xarray and Cartopy.

### PR DESCRIPTION
**Pull request by jhemedin**
Changed the GridMapDisplay class to use Xarray and it's plotting functions as well as using Cartopy for getting a basemap  background. Also created unit test for function.

### CODE REVIEW

**Comment by zssherman** [comment]
@rcjackson Hey, I added you as a reviewer if you have time. I suggested PEP8 changes, fixes, etc. Everything looks good to me, but just wanted a second set of eyes.

**Comment by jhemedin** [comment]
The get_dataset just creates an xarray dataset that is used for plotting. I can add a docstring if you think it is necessary.

**Comment by rcjackson** [comment]
For now we can just keep it as is.


Bobby

________________________________

**Comment by zssherman** [comment]
@scollis When you get this, seeing as your on travel, but once this is merged, I'll begin the release process.

**Comment by scollis** [comment]
In flight Wi-Fi ftw 

-sent from a mobile device-

**Comment by zssherman** [comment]
Hmm can't figure out why 3.5 is failing...

**Pull request merged**
