### PR TITLE
ADD: Animated GIF PPI Blog notebook

### PR DESCRIPTION
**Pull request by BrandonWeart**
This is the Making animated GIFs for radar PPI plots blog. This is in relation to the Summer 2024 SULI project and it covers a convective event over Lemont, IL on June 5th, 2024

- [ ] Closes #xxxx
- [ ] Tests added
- [ ] Documentation reflects changes

### CODE REVIEW

**Comment by zssherman** [comment]
Reopening to rerun tests now that the CI is fix.

**Comment by zssherman** [comment]
@BrandonWeart Looks like some linting issues https://github.com/ARM-DOE/pyart/actions/runs/9599719708/job/26474191833?pr=1598

**Comment by zssherman** [comment]
@BrandonWeart Also you need to add an author and date to the metadata of ipynb file. An example is:
```
 "metadata": {
  "author": "Max Grover",
  "date": "2024-03-21",
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
```
Yours is:
```
 "metadata": {
  "kernelspec": {
   "display_name": "CROCUS",
   "language": "python",
   "name": "crocusenv"
  },
```

**Comment by BrandonWeart** [comment]
I'm not sure why these linting checks aren't passing. Looking at my recent overwrite of the original file, the changes that pre-commit wants to impose here are the same ones pre-commit made on my local machine.

**Comment by zssherman** [comment]
@BrandonWeart Hmm that i'm not sure, let me think on that unless @mgrover1 has some thoughts?

**Comment by BrandonWeart** [comment]
Yeah its kinda strange. If you look at the most recent commit I made you can see the changes.

**Comment by zssherman** [comment]
@mgrover1 Worked with Brandon on getting the linter stuff fixed. Metadata is in the file as well, when you have a chance for a second review.

**Comment by BrandonWeart** [comment]
Hoping it's good!

**Review by mgrover1 — CHANGES_REQUESTED** [review]
Two very small comments - otherwise, looks great!

**Comment by BrandonWeart** [comment]
Hey Max I found the first instance of notebook needed to be changed to "blog post" but where is the second one?

**Comment by BrandonWeart** [comment]
Didnt mean to commit twice. Had an issue with my laptop for a second but it should all be done!

**Review by mgrover1 — APPROVED** [review]
Thanks for making those changes! Looks good to me!

**Pull request merged**
