### PR TITLE
FIX: Fix for only python 3.10 being used.

### PR DESCRIPTION
**Pull request by zssherman**

### CODE REVIEW

**Comment by zssherman** [comment]
Issue for wrong python version during tests has been fixed, still library issue with MacOS for PIL however

**Comment by zssherman** [comment]
Error seems to be addressed in https://github.com/conda-forge/libwebp-feedstock/issues/26
so looking through our installs to see if there is any reason why we are encountering this now.

**Comment by zssherman** [comment]
@mgrover1 This fixes only python 3.10 being used for all tests, also fixes pinning issues. However the current error is related to the PR above, however it has been fixed but can't seem to get it to work and it recently broke, so im curious if another release of theirs broke something.

**Review by mgrover1 — APPROVED** [review]
Good catch @zssherman

**Comment by mgrover1** [comment]
And the registry

**Comment by zssherman** [comment]
For the other PR? Sorry I don't follow @mgrover1

**Comment by mgrover1** [comment]
yup other PR sorry

**Pull request merged**
