### PR TITLE
MNT: Remove pandas pinning, testing.

### PR DESCRIPTION
**Pull request by zssherman**
- [ ] Closes #xxxx
- [ ] Tests added
- [ ] Documentation reflects changes

### CODE REVIEW

**Comment by zssherman** [comment]
@mgrover1 Do we know what the original issue was when we pinned pandas? Going to see if we can solve the issue or if it has resolved. Will respond back in a bit, heading to the dentist.

**Comment by mgrover1** [comment]
> @mgrover1 Do we know what the original issue was when we pinned pandas? Going to see if we can solve the issue or if it has resolved. Will respond back in a bit, heading to the dentist.

It was due to some of the datetime handling with xarray - looks like it is still an issue.

**Comment by zssherman** [comment]
@mgrover1 Ah gotcha, so there's nothing we can do on our end? it seems to be specifically that comp z test file

**Comment by zssherman** [comment]
@mgrover1 Think I found a solution

**Comment by mgrover1** [comment]
@zssherman ablog had a new update - checking to see if they're recommendations for fixing help.

**Comment by zssherman** [comment]
@mgrover1 Looks good! I'll merge ahead

**Comment by neutrinoceros** [comment]
The pin is causing failures in yt's CI (because pandas 1.5 uses API that's now deprecated in numpy 1.25). Any chance this would make it into a release soon ? We can work around it on our side otherwise, just let us know ! :-)

**Comment by mgrover1** [comment]
We can cut a release tomorrow! 😃

**Comment by zssherman** [comment]
@neutrinoceros The new release should be out now! I apologize for the late ping.

**Comment by neutrinoceros** [comment]
On the contrary, thank you very much for your reactivity !

**Pull request merged**
