### PR TITLE
FIX: Fixes a bug where set_rasterized is always True.

### PR DESCRIPTION
**Pull request by zssherman**
The if raster statement checks for 'if not None' False will count as this so set_rasterized will be True.

### CODE REVIEW

**Comment by scollis** [comment]
@nguy can you provide a quick comment as it touches airborne ?

**Comment by zssherman** [comment]
@scollis Sorry completely forgot to tag him.

**Comment by nguy** [comment]
I don't see any issues with this. Thanks @zssherman and @scollis !

**Comment by scollis** [comment]
Looks good.. merging

**Pull request merged**
