### PR TITLE
ADD: Ability to create a Py-ART Grid FROM an xarray object

### PR DESCRIPTION
**Pull request by rcjackson**
I have added a feature to convert an xarray object to a PyART Grid, essentially doing the reverse of what .to_xarray() does. This will help switching between PyART/Xarray grids more seamlessly.

- [x] Tests added
- [x] Documentation reflects changes

### CODE REVIEW

**Comment by zssherman** [comment]
@rcjackson Hmm looks to be a windows error.

**Comment by rcjackson** [comment]
> @rcjackson Hmm looks to be a windows error.

It's struggling with the temporary file. Looks to still be open when trying to reopen the file on Windows. Adding a ds.close() seems to fix this.

**Comment by zssherman** [comment]
@rcjackson Yeah weird windows things...

**Comment by zssherman** [comment]
@rcjackson build docs failure is unrelated, I have a fix in Joe's PR

**Review by mgrover1 — APPROVED** [review]
This looks great! Nice work @rcjackson

**Review by zssherman — APPROVED** [review]

**Pull request merged**
