### PR TITLE
FIX: The imp module was throwing a deprecation error for newer python versions

### PR DESCRIPTION
**Pull request by zssherman**
The package importlib is now being favored over imp, the following files have been changed to fix the warning in later python versions. Some functions from imp are either something else or do not exist in
importlib, changes have been made to accommodate this.

### CODE REVIEW

**Comment by scollis** [comment]
Thanks @zssherman I am going to let this sit for a little while.. Can you describe the issue you saw with Nose having a similar issue?

**Comment by zssherman** [comment]
This is the deprecation warning from nose. Nose still uses imp and the warning now goes from within pyart to nose.
```
site-packages/nose/importer.py:12: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses from imp import find_module, load_module, acquire_lock, release_lock
```

**Comment by scollis** [comment]
@zssherman closing and opening to run CI

**Comment by scollis** [comment]
Re-running CI by closing and opening

**Comment by zssherman** [comment]
@scollis I went through this again, and I didn't run into any issues. Also the recent commit fixes a issue with pytest in the __init__.py file were pytest.run needs to be pytest.main

**Comment by scollis** [comment]
I am just re-running Travis to make sure we are good to go

**Comment by scollis** [comment]
Tests passed, merging.

**Pull request merged**
