### PR TITLE
ENH: Addition of TDWR support.

### PR DESCRIPTION
**Pull request by zssherman**
Needed to add location info and checks as lat and lon are  3 decimal places off, and site altitude is too low. Interpolation needed to be added as 2:1 instead of the 4:1 spacing occurs. @HumphreysCarter can you let me know if this fix works for you?
This is what i was able to produce:
twdr_ref

### CODE REVIEW

**Comment by HumphreysCarter** [comment]
Wow, that was fast! That's working for me. Thanks @zssherman!

**Comment by zssherman** [comment]
@HumphreysCarter Awesome! @rcjackson, when you get a chance if you could do a quick review?

**Comment by rcjackson** [comment]
Looks good to me, Zach!

**Comment by zssherman** [comment]
Thanks @rcjackson merging.

**Pull request merged**
