### PR TITLE
Add Spectral-like colormaps based on pyart#1320

### PR DESCRIPTION
**Pull request by jthielen**
This PR implements a version of the `ChaseSpectral` colormap described in https://github.com/ARM-DOE/pyart/issues/1320 (configured with -10 dBZ as minimum and 80 dBZ as maximum, so that highest lightness occurs at roughly the midpoint of ~35 dBZ).

image

I also played around with some parameter smoothing and further lightness adjustments in CIELab space, and ended up with something that looks like matplotlib's "Spectral_r" colormap extended with "magma_r" on the high-end and a sequential-from-black colormap on the low-end. I called it `SpectralExtended`, and included it here as well.

image

### CODE REVIEW

**Comment by wx4stg** [comment]
love it! this weekend I'll be looking into converting these to GR/radarscope formats...

**Comment by zssherman** [comment]
Thanks @jthielen for putting this together! On the code side of things this looks good! I approved for the test suite to run, @mgrover1, we might want to consider in the future moving the .txt files to a dedicated directory.

**Review by mgrover1 — COMMENTED** [review]
One small suggestion - @jthielen can you add that new colormap to the example in the gallery? 
- [Link to example](https://arm-doe.github.io/pyart/examples/plotting/plot_choose_a_colormap.html#sphx-glr-examples-plotting-plot-choose-a-colormap-py)

**Review by zssherman — APPROVED** [review]

**Review by mgrover1 — APPROVED** [review]
Great! Thanks @jthielen !

**Pull request merged**
