### PR TITLE
Add balance CVD friendly colormap

### PR DESCRIPTION
**Pull request by scollis**
Adds the balance colormap from cmocean developed by @kthyng . Waiting for her ok if we can just direct include.. otherwise I will rollback. This colormap was found by our ERAD presentation to be the best CVD friendly velocity colormap.

### CODE REVIEW

**Comment by scollis** [comment]
Hey @rcjackson just give this a quick check when you are back in the office tomorrow.

**Comment by kthyng** [comment]
Yep please go ahead!

**Comment by rcjackson** [comment]
balance colormap test

Works like a charm!

**Comment by scollis** [comment]
Thanks @rcjackson merging

**Pull request merged**
