### PR TITLE
TST: Moving tests to test module within Py-ART main directory.

### PR DESCRIPTION
**Pull request by zssherman**

### CODE REVIEW

**Comment by mgrover1** [comment]
@zssherman I am pretty sure this has to do with the way the test configuration file is being used.

**Comment by zssherman** [comment]
Not sure about this new macos error

**Comment by zssherman** [comment]
@mgrover1 This should be good to go now, the error is unrelated to the PR.

**Review by mgrover1 — APPROVED** [review]
Once the final tests pass, this looks great! Thanks for all this hard work @zssherman

**Comment by zssherman** [comment]
@mgrover1 Oh just forgot, so would it be prune tests in manifest.in for ignore tests for the repo?

**Comment by mgrover1** [comment]
@zssherman yes!!

**Comment by zssherman** [comment]
@mgrover1 However, if they aren't included, how does conda forge test the package when its uploaded as a PR for a new release?

**Comment by mgrover1** [comment]
We don't need to explicitly include it - see https://github.com/Unidata/MetPy/blob/main/MANIFEST.in

**Comment by zssherman** [comment]
Ah gotcha, so just leave the manifest as is?

**Comment by mgrover1** [comment]
@zssherman I think so.

**Pull request merged**
