### PR TITLE
ENH: Added python 3.7, removed 32 bit testing, setting conda env path in attempt to fix issue finding dependencies.

### PR DESCRIPTION
**Pull request by zssherman**

### CODE REVIEW

**Comment by scollis** [comment]
Thanks... Lets see how it goes.. if it works I will accept and re-test @tjlang 's PR

**Comment by zssherman** [comment]
@scollis Not sure why on windows and python 2.7 for cfradial and nexrad cdm testing the tests files aren't being found. I skipped nexrad cdm for now, but not cfradial is coming up as a failure. I'll look into it.

**Comment by zssherman** [comment]
@scollis Cool beans, it all pass, this is ready to go.

**Comment by CAM-Gerlach** [comment]
@zssherman While you're at it, could you consider removing the ``sudo: false`` key? It's obsolete since the container-based infrastructure it triggers was removed from Travis CI a long time ago.

Also, is there a plan for a companion PR to update the Trove tags in ``setup.py`` so Python 3.7 compat and 3.4 non-compat is indicated properly in PyPI? Thanks.

**Comment by zssherman** [comment]
Thanks @CAM-Gerlach for the suggestions! I will update the setup.py file right now and remove sudo: false.

**Pull request merged**
