### PR TITLE
TST: Travis CI working with wradlib 0.7.0

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Just a reminder, the wradlib pypi version is _not_ the latest version with the changes. You would need to clone from master.

**Comment by jjhelmus** [comment]
@kmuehlbauer I plan on having Py-ART CI use the latest released version of wradlib not the bleeding edge.  0.7.0 is the latest release correct?

**Comment by kmuehlbauer** [comment]
Correct! But python2/3 compatibility will be reached with 0.8.0.

**Comment by jjhelmus** [comment]
I'll be limiting the tests to Python 2.7 at the moment.

**Comment by kmuehlbauer** [comment]
@jjhelmus, it seems that wradlib stalls in travis-ci in its setup.py, because some dependency is missing.  I suspect some gdal/netcdf issue. This will also be resolved with 0.8.0.

**Comment by jjhelmus** [comment]
Yes, the issue is with gdal, the package provided by Continuum is finicky.  I knew that this was failing just wanted a new CI run to debug.  Should have a fix shortly.

**Comment by kmuehlbauer** [comment]
Have a look here, this works for me: wradlib/wradlib#9

**Comment by jjhelmus** [comment]
The issue is that getting basemap and gdal to install correctly in a conda environment is difficult due to some of the packages incorrectly listing their dependencies, see ContinuumIO/anaconda-issues#584.

**Comment by kmuehlbauer** [comment]
@jjhelmus ah, I see, so wradlib works because of basemap is no dependency. BTW, did you experience kind of connection problems with the conda-repos lately?

**Comment by jjhelmus** [comment]
They seems a bit slow last night for me (~12 hours ago) but I haven't had any problems today.

**Comment by kmuehlbauer** [comment]
OK, because I had some problems 5/6 days ago, where packages were not correctly installed within travis.

**Comment by jjhelmus** [comment]
FYI, I created conda packages for wradlib 0.7.0 and uploaded them to by [Anaconda.org channel](https://anaconda.org/jjhelmus/wradlib).  I'll be making a [conda-forge](https://conda-forge.github.io/) pull request shortly for a more maintainable solution.

**Pull request merged**
