### PR TITLE
FIX: Fix for cftime 1.5 release.

### LINKED ISSUE #993: Unidata removed utime class from cftime
Unidata removed utime class from cftime which will break this line https://github.com/ARM-DOE/pyart/blob/8c838bc823436e2397253fb66b06d47c42c43816/pyart/aux_io/sinarame_h5.py#L13
https://pypi.org/project/cftime/1.5.0/
`Some legacy classes and functions removed (utime, JulianDayFromDate and DateFromJulianDay). The functionality of JulianDayFromDate and DateFromJulianDay is now available from the methods cftime.datetime.toordinal and cftime.datetime.fromordinal.`

### PR DESCRIPTION
**Pull request by zssherman**
Fixes the removal of cftime utime legacy code, reproduces similar cftime use in other modules. Fixes #993

### CODE REVIEW

**Comment by zssherman** [comment]
Tests passed, doesn't say on the PR but on Travis, so merging.

**Comment by amarouane-ABDELHAK** [comment]
Thank you for fixing this, we are installing pyART with conda `conda install -c conda-forge arm_pyart`. When do you think this release will be available for us to pick up (using conda)?.

**Comment by zssherman** [comment]
@amarouane-ABDELHAK I should have it sometime in the next couple of hours.

**Comment by zssherman** [comment]
@amarouane-ABDELHAK The conda release is done, usually takes 10-15 minutes for the site to upload everything, so say give it that, and check for the 1.11.5 release

**Comment by zssherman** [comment]
@amarouane-ABDELHAK New release is now on conda-forge and should be installable now

**Comment by amarouane-ABDELHAK** [comment]
Thank you, worked as expected.

**Pull request merged**
