### PR TITLE
Write grid mdv

### PR DESCRIPTION
**Pull request by gamaanderson**
One PR closes, an other opens. But I do think all issue that may emerge are easy fix, I simplify add functions `write_grid_mdv` and `read_grid_mdv`.

There is this thing with encoding, I forget to write in the documentation but float64 is being casted to float32, there is a hack to allow other encoding available in MDV file, but a much better solution can be done following PR #266 and issue #278, when that is merged.

Pay attention that I'm importing *mdv.py* as  `import mdv as MDV`, I know this is bad, but I needed some constants defined there. Please change that to what you consider better.

You may also consider moving `read_mdv` from *mdv.py* to *mdv_io.py*.
 
Finally, the git history is a mess, you may rebase if you want, I'm not familiar in doing that.

### CODE REVIEW

**Comment by jjhelmus** [comment]
This will make another great addition and will make adding unit tests for the writing function of **MdvFile** much easier.  I need to see to a few other tasks before I can review this but hopefully should be later today or Monday at the latest.

**Comment by jjhelmus** [comment]
Also ignore the failing coverage test, I have no idea why that started popping up and need to figure out how to disable it.

**Comment by gamaanderson** [comment]
sounds good.

**Comment by jjhelmus** [comment]
I reverted (undid the commits) in PR.  When writing unit tests for the new code there were a number of bugs that need to be address before this is merged into the master.  Sorry for not checking these before merging.  @gamaanderson If you can create a new PR I'll outline the issues and submit a PR with some failing tests to highlight some of the issues.

**Comment by gamaanderson** [comment]
done, PR #297. I had to do it by hand, hope is everything right

**Pull request merged**
