### PR TITLE
ADD: Addition of above_toa_filter.

### LINKED ISSUE #442: The toa parameter is interpreted differently in the two gridding methods
The `toa` parameter control the height above which gates are excluded from the gridding algorithm.  This parameter is interpreted differently by the two gridding routines.  

In the 'map_gates_to_grid' the distance of the gate above the radar is added to the offset of the radar from the grid and compared against toa (toa is the height above grid origin).  

In 'map_to_grid' the distance of the gates above the radar is compared directly to toa (toa is the height above the radar).  

A uniform interpretation of toa should be used in both gridding methods.

### PR DESCRIPTION
**Pull request by zssherman**
This filter replaces toa parameter in gridding code and allows for the user to specify their own remove above toa filter by using the gatefilter for consistency between both gridding functions.

- [x] Closes #442 
- [x] Documentation reflects changes

### CODE REVIEW

**Comment by zssherman** [comment]
@mgrover1 Question is, do we continue if gatefilter is None, remove anything above 17000.0 for gridmapper, or leave it fully up to the user

**Comment by zssherman** [comment]
@mgrover1 Changes have been done for backwards compatibility, this should be good now for a final review.

**Comment by zssherman** [comment]
@mgrover1 When you get a chance, this is good for a final review

**Review by mgrover1 — CHANGES_REQUESTED** [review]
Can we keep the toa parameter in `map_gates_to_grid`, and remove when we release in 2.0?

**Comment by zssherman** [comment]
@mgrover1 The only reason I removed it from the map_gates_to_grid but not grid mapper is that in map_gates_to_grid I did not see the parameter being used anywhere when I search for toa so I believe it was just there.

**Comment by zssherman** [comment]
@mgrover1 Added it back in.

**Comment by mgrover1** [comment]
the failing test is fixed in #1597

**Review by mgrover1 — APPROVED** [review]

**Pull request merged**
