### PR TITLE
FIX: odimh5 range and azimuth sampling

### PR DESCRIPTION
**Pull request by vlouf**
Fix for issue #897

### CODE REVIEW

**Comment by scollis** [comment]
@zssherman please review. Let us know the impact of this change in terms of impact of gate data.. if there is a noticeable difference in smoothness make us a PPI plot zoomed right into the gate level

**Comment by scollis** [comment]
Thanks @vlouf ! A most welcome PR.. @zssherman has been assigned to review. Tests have passed.

**Comment by zssherman** [comment]
Using the odim h5 file I have, there was no difference in the gate data between sets of code.

**Comment by vlouf** [comment]
@zssherman If the astart value in your odim file is -0.5 (or any value that is offseted by half of the beamspacing) then the original code would have produce the right azimuth sampling.

**Comment by scollis** [comment]
Ok! @zssherman can you officially approve ?

**Comment by zssherman** [comment]
No problem, it has been approved.

**Pull request merged**
