### PR TITLE
DEP: Changed fromstring to frombuffer to removed depreciation.

### PR DESCRIPTION
**Pull request by zssherman**
Changed all files, but nexrad2 (already addressed in #700) in pyart that needed np.fromstring changed to np.frombuffer. We'll see what the tests show. Should only show basemap and nexrad2 with warnings because basemap is a dependency and the nexrad2 pull request is pending. If anything looks off let me know.

### CODE REVIEW

**Comment by scollis** [comment]
Thanks @zssherman 
I'll pull down the branch and test locally to make sure it is just Basemap and nexrad causing us issue.

**Comment by scollis** [comment]
Ok.. I am going to Merge this and then #700.. wish me luck

**Comment by scollis** [comment]
Before I merge @zssherman Have you checked a UF file with this yet? 
Let me know if you need one.

**Comment by scollis** [comment]
@zssherman I checked reflectivity on MDV and UF and it looks good.

**Comment by dopplershift** [comment]
@scollis You should add a test to automate whatever it was that you just checked. Either image test with pytest-mpl, or pick a few random bins and check the values.

**Comment by scollis** [comment]
@zssherman checked sigmet and it is good..
I think this coverers our main ingests

**Comment by zssherman** [comment]
@scollis Hi I do not have a uf file, I probably should have said lets not merge until we are certain. @dopplershift, good idea. I was going to say the failing 2.7 doc build environment not sure why it is failing. The log and raw log are still too large to see other errors besides depreciation warnings still.

**Comment by zssherman** [comment]
Glad they are looking good so far...

**Comment by scollis** [comment]
@dopplershift We do.. we have some test files we do things like min/max .. I need to take a look to see how much they are capturing 
eg https://github.com/ARM-DOE/pyart/blob/master/pyart/io/tests/test_sigmet.py#L273

**Comment by scollis** [comment]
Ok.. I am happy.. Merging.

**Pull request merged**
