### PR TITLE
Gatefilter functionality for plot_ray

### PR DESCRIPTION
**Pull request by swnesbitt**
This pull request adds `gatefilter` functionality to `plot_ray` as an optional argument.  Please ignore the garbage earlier than today, as I am just learning about branches. :)

```python
gf = pyart.correct.GateFilter(iradar, exclude_based=True)
gf.exclude_masked('reflectivity')
gf.exclude_below('reflectivity', 0.0, inclusive=False)
gf.exclude_below('cross_correlation_ratio', 0.8, inclusive=False)

display = pyart.graph.RadarDisplay(iradar)

display.plot_ray('reflectivity',idx,gatefilter=gf)
```
download

### CODE REVIEW

**Comment by jjhelmus** [comment]
Looks good to me, are the only changes in commit e873c56?  Would it be alright if I cherry-pick that commit to keep the revision history cleaner?

**Comment by swnesbitt** [comment]
Yes, cherry pick away

On Tuesday, April 12, 2016, Jonathan J. Helmus <notifications@github.com>
wrote:

> Looks good to me, are the only changes in commit e873c56
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ARM-2DDOE_pyart_commit_e873c566bdf9ac7320bb246a88002b18e0d9d1f6&d=BQMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=oh_IyBh3p6AhkrNBZyzmmDfeXg2WKrzfthPLOoHreWM&m=-aDB4Ph2iyrj23j6XGP2ae54k-CfHtiXh6iZHRDmMr4&s=_G1K_4sCoj04Szdemi96SA77maH2TrG4mxobGrCmAZs&e=>?
> Would it be alright if I cherry-pick that commit to keep the revision
> history cleaner?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ARM-2DDOE_pyart_pull_518-23issuecomment-2D208969219&d=BQMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=oh_IyBh3p6AhkrNBZyzmmDfeXg2WKrzfthPLOoHreWM&m=-aDB4Ph2iyrj23j6XGP2ae54k-CfHtiXh6iZHRDmMr4&s=43OeG0SomQV2C_2bsdGHjLwOtdN1Mk3z3LMXQXJPwlQ&e=>
>


-- 
Steve Nesbitt, Associate Professor
Department of Atmospheric Sciences, University of Illinois at
Urbana-Champaign
105 S. Gregory St., MC223, Urbana, IL 61801-3070  USA
voice : +1.217.244.3740  fax : +1.217.244.1752
internet : snesbitt@illinois.edu ;
https://www.atmos.illinois.edu/people/snesbitt ;
http://publish.illinois.edu/snesbitt

**Comment by jjhelmus** [comment]
Cherry-picked onto ARM-DOE/master as commit c6ea0835f.  Thanks for the contribution @swnesbitt.

**Comment by scollis** [comment]
+1

this will be nice for tuning gate filters. 



Dr Scott Collis
Purveyor of lofty observations (Atmospheric Scientist) 
Environmental Science Division
Argonne National Laboratory
Mb: +1 630 235 8025
Of: +1 630 252 0550
Become a Py-ART user today! http://arm-doe.github.io/pyart/ <http://arm-doe.github.io/pyart/>

**Pull request closed without merging**
