### PR TITLE
MAINT: Temp fix for warnings in colormap modules.

### PR DESCRIPTION
**Pull request by zssherman**
From what I'm reading, there is some disagreement between numpy and python on comparisons. For now I added a ignore warning until I can find maybe a better solution.

### CODE REVIEW

**Comment by zssherman** [comment]
Tests past, merging.

**Comment by kenkehoe** [comment]
@zssherman  can you make a release version for this update. The ARM DQ Office is using PyART on ARM ADC production system and would like to implement this update. We use the official tagged release from Git for our install process with RPM and YUM.

**Comment by zssherman** [comment]
@kenkehoe No worries, I will do a release shortly.

**Comment by zssherman** [comment]
@kenkehoe I did a new release, 1.10.2. Everything got approved and should be appearing on conda-forge shortly.

**Comment by kenkehoe** [comment]
@zssherman wonderful. Thank you!

**Pull request merged**
