### PR TITLE
DOC: Update INSTALL.rst file

### PR DESCRIPTION
**Pull request by jjhelmus**
* Update supported Python versions
* Remove minimum versions from other packages
* Update URL for netcdf4-python

### CODE REVIEW

**Comment by dopplershift** [comment]
Do you no longer have specific versions of numpy/scipy you support?

**Comment by jjhelmus** [comment]
In all truthfulness I don't know what the minimum versions of numpy/scipy are for Py-ART.  Older versions should work fine or will give a loud error when trying to use some "new" API feature but I have not extensively tested how far back this can go.  

Checking a few version of numpy with conda, I found that NumPy 1.9 is required for the unit tests to pass, but the failures from older versions (1.8 and 1.7) are likely caused by test which expect an over ambitious precision and an minor API change in matplotlib which I doubt would effect actual use of the package.  NumPy 1.6 fails a few more tests but against mostly due to minor precision issues and a few API changes. 

Is it worth putting in the time to track down and fix any bugs so that exact minimum version of Py-ART dependencies can be specified?  It definitely could be done, and a Travis job could be added to run tests in this minimum environment, but I'm not sure if the payoff would be worth the effort.

**Comment by dopplershift** [comment]
Makes sense...I was just curious.

**Comment by jjhelmus** [comment]
I think I'll leave it as is, if there is a call for more details on minimum versions this can be revisited.

**Pull request merged**
