### PR TITLE
FIX: use max_num_gates for calculation of data shape

### PR DESCRIPTION
**Pull request by kmuehlbauer**
solves #1336 

But only if range resolution is same for all sweeps.

### CODE REVIEW

**Review by zssherman — APPROVED** [review]
This looks good @kmuehlbauer! Thanks for putting this together!

**Comment by tsbiscaro** [comment]
#1337 

That works for reading the data, but it will crash during the plot (I am trying to plot the first elevation):

 File "dual_pol.py", line 15, in <module>
    display.plot('corrected_reflectivity', 0, vmin=20, vmax=70., colorbar_label='dBZ', axislabels_flag=False)
  File "/home/tbiscaro/anaconda3/envs/radar/lib/python3.8/site-packages/pyart/graph/radardisplay.py", line 138, in plot
    self.plot_ppi(field, sweep, **kwargs)
  File "/home/tbiscaro/anaconda3/envs/radar/lib/python3.8/site-packages/pyart/graph/radardisplay.py", line 337, in plot_ppi
    pm = ax.pcolormesh(
  File "/home/tbiscaro/anaconda3/envs/radar/lib/python3.8/site-packages/matplotlib/__init__.py", line 1423, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/tbiscaro/anaconda3/envs/radar/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 6133, in pcolormesh
    X, Y, C, shading = self._pcolorargs('pcolormesh', *args,
  File "/home/tbiscaro/anaconda3/envs/radar/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 5661, in _pcolorargs
    raise TypeError('Dimensions of C %s are incompatible with'

A sample file can be downloaded at: https://1drv.ms/u/s!AjzwFqty9OKPiPwNlxYAGzNyHDoLfQ?e=WUk03I

**Comment by kmuehlbauer** [comment]
Yes, what a pity, I've missed to fix the range as well. I'll add the needed changes.

Thanks for the data file. I can confirm, that the range resolution changes in your file between sweeps. That contradicts the current Py-ART CfRadial1-based datamodel. 

@zssherman @mgrover what's the current workaround in that case?

**Comment by tsbiscaro** [comment]
Yes, the range varies too. I've contacted the radar operator to change this because it doesn't make sense to me, but I've sent the file anyway as a good test file for reading a really bad-formatted file...

**Comment by kmuehlbauer** [comment]
I would not say it's bad formatted. It makes sense to decrease the range resolution with increasing elevation which results in better height resolution for higher angles. That's one reason CfRadial2 was invented, a data model also Py-Art will switch to, with the help of `xradar`.

**Pull request merged**
