### PR TITLE
Initial version of CSU D3R radar reader

### PR DESCRIPTION
**Pull request by swnesbitt**
This version of the code, placed in aux_io, reads the raw Ku and Ka netCDF files for the
GCPEx field campaign.  My understanding is that the D3R format has been
under revision and may be different field campaigns, but I have tested
for GCPEx and it seems to work.  Comments/improvements welcome.

### CODE REVIEW

**Comment by swnesbitt** [comment]
Example RHI at Ku Band
image

**Comment by jjhelmus** [comment]
@swnesbitt Thanks for adding this.  I'll fix the style and documentation a bit after merging but looks great!

**Comment by jjhelmus** [comment]
@swnesbitt FYI, in PR #291 I made a few minor changes to the code to clean up style, remove a few unneeded variables/imports and added the the new functionality to the documentation.  If you are interested in making these edits in the future let me know and I'll provide a review, if not I'm happy to do the clean up.

I use [pep8](https://pypi.python.org/pypi/pep8) to check the style and [pylint](http://www.pylint.org/) to check for code unnecessary lines of code and other smells.

Thanks again for the contribution!

**Comment by swnesbitt** [comment]
Thanks – I’ll check out pep8 and pylint. Style points were never my forté…

-Steve
--
Steve Nesbitt
Associate Professor
Department of Atmospheric Sciences
University of Illinois at Urbana-Champaign
105 S. Gregory St., MC223
Urbana, IL  61801-3070  USA
voice : +1.217.244.3740  fax : +1.217.244.1752
e-mail : snesbitt@illinois.edu<mailto:snesbitt@illinois.edu>
web : http://publish.illinois.edu/snesbitt

Spring Semester 2015:
Visiting Professor, Departamento de Ciencias de la Atmósfera y los Océanos-Centro de Investigationes del Mar y la Atmósfera, CONICET-Universidad de Buenos Aires
Visiting Scientist, Servicio Meteorológico Nacional, Argentina

From: "Jonathan J. Helmus"
Reply-To: ARM-DOE/pyart
Date: Friday, May 15, 2015 at 8:48 AM
To: ARM-DOE/pyart
Cc: Steve Nesbitt
Subject: Re: [pyart] Initial version of CSU D3R radar reader (#289)


@swnesbitt<https://github.com/swnesbitt> FYI, in PR #291<https://github.com/ARM-DOE/pyart/pull/291> I made a few minor changes to the code to clean up style, remove a few unneeded variables/imports and added the the new functionality to the documentation. If you are interested in making these edits in the future let me know and I'll provide a review, if not I'm happy to do the clean up.

I use pep8<https://pypi.python.org/pypi/pep8> to check the style and pylint<http://www.pylint.org/> to check for code unnecessary lines of code and other smells.

Thanks again for the contribution!

**Pull request merged**
