### PR TITLE
Fix wradlib 

### LINKED ISSUE #722: wradlib release 1.0.0
wradlib release 1.0.0 is on it's way. There are breaking changes in this version which also effect pyart rainbow reader. The changes were due to PEP8 conformity, so everything will work after introducing these changes.

I will introduce the necessary changes next week via PR. Sorry for any inconvenience.

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- closes #722 
- fixes links to wradlib
- fixes import of `read_rainbow`

### CODE REVIEW

**Comment by scollis** [comment]
Thanks @kmuehlbauer !! @zssherman can you review.. Download the branch and make sure we can still read X-SAPR2

**Comment by zssherman** [comment]
Sounds good, doing that now.

**Comment by kmuehlbauer** [comment]
@zssherman only rainbow is effected.

**Comment by zssherman** [comment]
@kmuehlbauer Makes sense. Ah I notice that link changes, I changed the wradlib link in the README, didn't realize there were more. Glad you caught those. @scollis The changes look good to me and the CI is passing, I just need some rainbow data if you want me to be completely sure.

**Comment by kmuehlbauer** [comment]
@zssherman there is one rainbow file in wradlib/wradlib-data repo on github, if you want to test.

**Comment by kmuehlbauer** [comment]
@zssherman Only the function name changed, no functionality. Should work.

**Comment by zssherman** [comment]
Perfect! Thanks @kmuehlbauer !

**Comment by scollis** [comment]
Ahh cool.. for some reason I thought GAMIC had rainbow as an underlying format.. @zssherman just double check using the rainbow file..

**Comment by scollis** [comment]
Thanks! accepting

**Comment by meteoswiss-mdr** [comment]
Hi all,

@kmuehlbauer , @scollis, there was an issue with the wradlib library. When passing the file name instead of the file handle the file was not properly closed after reading. That issue has been corrected but it did not make it to version 1.0 of wradlib so whoever uses wradlib 1.0 in Py-ART (as myself) will not close the files properly
I propose to solve the issue by passing the file handle, not the file name to wradlib, i.e.:
with open(filename, 'rb') as fid:
        rbf = read_rainbow(fid, loaddata=True)
Greetings from Switzerland!

**Comment by scollis** [comment]
Good morning @meteoswiss-mdr ! Sounds like a good change. Feel free to submit a PR or we can do so next week (DoE meeting this week).

**Comment by meteoswiss-mdr** [comment]
It is such a small change that I let you do it yourselves.

**Pull request merged**
