### PR TITLE
FIX: Fixes an issue with mismatch arrays.

### PR DESCRIPTION
**Pull request by zssherman**
When using sonde profiles, when it resets the variable with the same name, get issues due to the shape mismatch. Creating an array with same shape as the no_nan array.

### CODE REVIEW

**Review by mgrover1 — CHANGES_REQUESTED** [review]
Good catch - would you be willing to add a test here to verify this is working as expected?

**Comment by zssherman** [comment]
Ah i forgot awhile back I added a skip because I ran into an issue, let me remove the skip and see if this fixes the failure from the past.

**Comment by zssherman** [comment]
I sim_vel unittests should run again now

**Comment by zssherman** [comment]
Now I remember why i skiped at the time, its not finding simulated_velocity despite it being in the config lol, I remember I was scratching my head for awhile on this one

**Comment by mgrover1** [comment]
@zssherman looks like it's having an issue with some attribute?

**Comment by zssherman** [comment]
Yeah we are getting incredibly odd behavior with this test. The attribute is a scipy error, that same code is called in other tests in pyart and does not fail. This test also fails when trying to find simulated velocity field name, neither of these fail locally, none of this makes sense at all

**Comment by zssherman** [comment]
I think this is why i skipped it before, because the tests being pull by pytest for simulated velocity won't work correctly

**Comment by mgrover1** [comment]
Good to merge @zssherman ?

**Pull request merged**
