### PR TITLE
Add transparency to plot methods and despeckle issue

### PR DESCRIPTION
**Pull request by tjlang**
While most plot* iterations allow the alpha keyword to be passed to the
pcolormesh call at the heart of the method, due to the **kwargs
inclusion, the plot_ppi_map methods in RadarMapDisplay and
RadarMapDisplayCartopy did not. This has been fixed.

### CODE REVIEW

**Comment by tjlang** [comment]
Also added a fix for https://github.com/ARM-DOE/pyart/issues/636

**Comment by scollis** [comment]
Thanks Tim .. will checkout tomorrow 

-sent from a mobile device-

**Comment by scollis** [comment]
Sorry for letting this linger @tjlang I am going to close and open this to let the CI run again.

**Comment by scollis** [comment]
For some reason Travis ran and not Appveyor.. closing and opening again.

**Comment by scollis** [comment]
@tjlang You wrote the iphex noxp ingest right? 
All unit tests have passed. I do want to do a test merge locally and investigate the alpha behaviour but this looks good.

**Comment by tjlang** [comment]
Yes I wrote the NOXP ingest for IPHEx.

**Comment by scollis** [comment]
@zssherman can you help @mhpicel in testing this PR?

**Comment by scollis** [comment]
I am going to do a quick close and open to re run CI.. @tjlang Any reason not to merge?

**Comment by tjlang** [comment]
No, go ahead.

**Comment by scollis** [comment]
Sweet. We fixed a quick issue with doc generation now tests pass.. Thanks @tjlang and sorry for the delay!

**Pull request merged**
