### PR TITLE
ENH: Adding get_gate_lat_lon_alt function.

### PR DESCRIPTION
**Pull request by zssherman**
Mentioned in #808 by @aschueth, function allows the user to specify a sweep and can then obtain the gate latitude, longitude and altitude for that sweep.

### CODE REVIEW

**Comment by zssherman** [comment]
Will commit unit tests shortly.

**Comment by scollis** [comment]
Quick thought @zssherman : I wonder if we should have an option in the code to force the recalculation of the underlying data.. Right now if a user alters geometry (eg radar alt) you need to call a method of radar to force recalc

**Comment by zssherman** [comment]
@scollis I added the reset coords function that will recalculate the gate coords as an option.

**Comment by scollis** [comment]
@rcjackson any comments?

**Comment by rcjackson** [comment]
This all looks good to me. Having the altitude and lat and lon in one function is certainly very helpful.

**Comment by scollis** [comment]
Thanks @zssherman !! Merging

**Pull request merged**
