### PR TITLE
FIX: This converts the nexrad altitude from feet to meters.

### PR DESCRIPTION
**Pull request by zssherman**
@dcedgren this should address #922 for nexrad level 3

### CODE REVIEW

**Comment by zssherman** [comment]
@scollis This would address the altitude units being feet and converting to meters, but would we want users to set altitude units to feet to keep those units? Would this cause issues in gridding and coordinate conversions?

**Comment by dcedgren** [comment]
@zssherman Just a note that you may be confusing altitude and elevation. I think you meant this most recent commit to go on the other pull request.

I would vote against putting the warning on elevation being none where you did. If you put it in the IO module any time a user imports a Nexrad Level III product that's not in a certain list it's going to trigger the warning. If I didn't have context I think I might worry that something didn't import correctly with the text of the warning. Instead, why don't you make it an error and put it at the location where they actually try to plot an RHI with it, which would be undefined for that product?

**Comment by dcedgren** [comment]
Ok, makes sense.

**Comment by rcjackson** [comment]
It looks solid to me. Thankfully this was caught! Do we know if the previous version's gridding was impacted in any way?

**Comment by zssherman** [comment]
@rcjackson I'm honestly not sure.

**Comment by rcjackson** [comment]
I think it probably does, given that the altitudes are probably a factor of 3 too high. Therefore, I would put out a notice of this fix to pyart-users warning anyone using NEXRAD Level 3 data that the altitudes (in m) are off by a factor of ~3 due to this unit conversion. The users should regenerate any grids they made from NEXRAD L3 data as a precaution.

**Comment by zssherman** [comment]
Sounds good, I'll put out a warning. And merge for now, thanks @dcedgren @rcjackson

**Pull request merged**
