### PR TITLE
ADD: added a function that will make a QVP object from a radar object 

### PR DESCRIPTION
**Pull request by jhemedin**
Code is based on adapted code from Scott Collis using the method found in Ryzhkov et all (2013, 2014, 2015)

Function will create a QVP dictionary with fields from a radar object. Testing of the code was done using radar scans and creating a time series plot and well as testing it against the unit test. 

Attached are some example time series plots
reflectivity_no_gatefilter
zdr_with_rhv_gatefilter
ref_with_gate_id_gatefilter

### CODE REVIEW

**Comment by zssherman** [comment]
Hmm, the python 3 errors seem to be involved with basemap, which will be fixed soon. The 2.7 error seems to be similar to the pyart google group install error with Anaconda2. I'll see If I can find out why the 2.7 test is failing.

**Comment by scollis** [comment]
Yes. Matplotlib will release a 3.0.2 tomorrow we hope.

**Comment by scollis** [comment]
Closing and opening to force appveyor to retest

**Comment by scollis** [comment]
@jhemedin ..
looks like you have a non-ascii character carried over from a cut and paste
```E   SyntaxError: Non-ASCII character '\xe2' in file /home/travis/build/ARM-DOE/pyart/pyart/retrieve/qvp.py on line 54, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details```

**Comment by scollis** [comment]
https://github.com/ARM-DOE/pyart/pull/783/files#diff-fa0fe274e84c79942a6667f60b9ac11cR54

**Comment by zssherman** [comment]
Only at 2.7 issue, hmm. Wonder if it is similar to the decode issue that Valentin found in the pass? I'll see what I can find out.

**Comment by scollis** [comment]
Woot! CI passed! Merging. Thanks @jhemedin

**Comment by meteoswiss-mdr** [comment]
Hi @scollis!

It is great that there is now a QVP object in Py-ART! In my own Pyrad I have coded a whole family of QVP-like objects. Perhaps you can have a look here:

https://github.com/meteoswiss-mdr/pyrad/blob/master/src/pyrad_proc/pyrad/proc/process_timeseries.py

I can ask somebody in my team to spent some time adapting the code to the QVP object you just created.

By the way, we never created the list of priorities for pull request we talked about. When you are ready let me know.

Greetings from Switzerland!

**Comment by scollis** [comment]
Hey Jordi! Yeah.. I need to step up our collaboration.. Perhaps I need to visit next year. 

We will get better at this soon. Please have your person work with us we are only too happy

**Comment by meteoswiss-mdr** [comment]
OK, we will migrate the code to Py-ART as soon as possible.

Feel free to visit us whenever you want.

**Pull request merged**
