### PR TITLE
fix of circular reference in Radar and Grid Class

### PR DESCRIPTION
**Pull request by hhuangwx**
fix of #696 

"The LazyLoadDict used in the Radar class causes a circular reference, which will make the memory used by the class never collected by the automatic gc system (known as the memory leakage)."

The LazyLoadDict is removed and the relevant parts are refactored in the Radar and Grid Class in this PR. The other codes using LazyLoadDict (e.g. the mdv class) are not changed.

### CODE REVIEW

**Comment by scollis** [comment]
Thank you @hhuangwx ! Much appreciated! 
@zssherman please review. @hhuangwx will this kill our ability to load a file without reading the moments?
We will take a look! I wonder if we are better off leaving the lazy load methods in and only having them used when a partial load is done.. These were implemented by @jjhelmus

**Comment by hhuangwx** [comment]
I think the delay_field_loading used in read_cfradial is not affected by this PR. The circular reference is caused by fact that the functions used by LazyLoadDict point back to the Radar or Grid Class again. In the delay_field_loading function, the function used by LazyLoadDict points to the ncobj, which will not cause the circular reference. It'll be more elegant if anyone figures out a way to fix the circular references without removing the lazy loading in Radar and Grid.

**Comment by hhuangwx** [comment]
I think the potential solution for the delayed loading is to use functions with the "property" decorators as the attributions (e.g., gate_x). The computations to get the attributions are delayed until we call/use the attributions. Actually, the LazyLoadDict shares the same philosophy with this idea.

**Comment by scollis** [comment]
Thanks @hhuangwx @zssherman needs to investigate why the CI failed as well. It is very important we maintain compatibility with users existing workflows and not break them

**Comment by dopplershift** [comment]
Why do you think circular references cause memory leaks? Python has a garbage collector it runs whose sole purpose in life is to collect circular references and avoid memory leaks:

https://pythoninternal.wordpress.com/2014/08/04/the-garbage-collector/

**Comment by scollis** [comment]
Closing and opening to force run unit tests

**Comment by hhuangwx** [comment]
@dopplershift You're right about the ability that the standard library "gc" can collect the garbage if we explicitly call it. However, "Python doesn’t collect such cycles automatically " according to the document of the gc library. That's the reason I think we should break the reference cycles to avoid the manual gc procedures.

image

**Comment by scollis** [comment]
@hhuangwx are you able to run the nosetests locally? I see a lot of issues on the CI.

**Comment by hhuangwx** [comment]
I'll try the nosetests. @scollis

**Comment by jjhelmus** [comment]
Neither the Radar class nor the LazyLoadDict class have a `__del__` method so the Python garbage collector will have no issue collecting the cyclic references automatically.

If there is a desire to break the circular reference, passing a `weakref.proxy` instance to the factory function should work.

**Comment by scollis** [comment]
Thanks @jjhelmus ! 
@hhuangwx I want to know more about the specific problems this is causing you. We appreciate your contribution but LazyLoadDict was designed to enable partial loading of radar files and the building of data models where calculations could be performed later. What you are proposing is a pretty big change so we need a careful review.

**Comment by hhuangwx** [comment]
Thanks @jjhelmus @scollis. I'm kind-of busy these days. I'll perform additional test about the memory when I'm free.

**Comment by scollis** [comment]
Absolutely no hurry. 

-sent from a mobile device-

**Comment by scollis** [comment]
I am going to close this for now. If anyone gets back to this we can reopen

**Pull request closed without merging**
