### PR TITLE
Gridding handles 1D radar lat, lon, alt

### PR DESCRIPTION
**Pull request by rtanamachi**

### CODE REVIEW

**Comment by scollis** [comment]
Thanks @rtanamachi ! Great idea. @zssherman can you review please. Check for backward compatibility on the cases you are running.

**Comment by zssherman** [comment]
Sounds good! I will take a look.

**Comment by zssherman** [comment]
Hi @rtanamachi , thanks for the pull request! Just had two questions, do you have a file I can test both versions on? Second was, for the trys and except, for the 1D radars, does it always throw a ValueError and go to the except or does the error vary?

**Comment by rtanamachi** [comment]
This example file is one tilt from a volume containing 30 tilts total.
[cfrad.20180602_003753.958_to_20180602_003756.720_UMassLPR_PPI.nc.gz](https://github.com/ARM-DOE/pyart/files/2450921/cfrad.20180602_003753.958_to_20180602_003756.720_UMassLPR_PPI.nc.gz)
I don't recall if it's *always* a ValueError that's raised, but I think it probably is.

**Comment by rtanamachi** [comment]
A typical invocation would be:
theGrid = pyart.map.grid_from_radars(radars, grid_shape = (60,60,60), grid_limits = ((0,10000),(0,15000),(-15000,0)), fields = ['ZH'])

**Comment by scollis** [comment]
Thanks @rtanamachi .. To expand on what Zach was saying, having a simple "Try, Except" in the code can lead to unforeseen mental breakdowns.

When using Python exceptions good (but often violated, including by myself) practice is:
```
try:
    some_code
except SomeError:
    someothercode
```

the reason being if some_code throws an error you were not fixing in the Pull Request it can be very hard to track it down lates as a blanket except is moving onto someothercode.

**Comment by scollis** [comment]
@zssherman will see what the exact errors are and the submit a PR against your fork/branch. Once you accept this it will update this PR.. Magic of distributed version control :)

**Comment by rtanamachi** [comment]
Strictly speaking one might not even need to do the try-except clause, as the mean of a scalar is just the scalar. The try-except is just to save some extra computation involved in np.mean

**Comment by scollis** [comment]
Hey @rtanamachi We'll get to this soon. Zach is taking some vacation days.

**Comment by zssherman** [comment]
@rtanamachi Are the values in the 1D lat lon and alt arrays ever different? Or does the radar data produced from the radar just have 1D arrays of the same values? Because if they don't change, another option is just set for example:
```python
grid_origin_alt = radars[0].altitude['data'])
 ``` 
to
```python
grid_origin_alt = radars[0].altitude['data'][0])
```
And works the same. For the radar you sent me and a radar we've been working with, but only works if the arrays are the same values throughout the array.

**Comment by rtanamachi** [comment]
For a stationary radar, the lat, lon, and alt would not change mid-sweep. However, for a translating (mobile or airborne radar) they might. In the latter case, taking np.mean would be a poor choice anyway, and you'd have to grid on a ray-by-ray basis.

**Comment by zssherman** [comment]
@rtanamachi Was going to do a pull request to your branch, but getting some conflict errors. With that branch can you do a git pull and get the recent pyart changes and push to github? Want to see if that will fix it.

**Comment by zssherman** [comment]
@rtanamachi I submitted a pull request to your branch. If everything looks good and is accepted. This CI will rerun here and it should be good to go.

**Comment by scollis** [comment]
@rtanamachi are you able to accept @zssherman 's PR against your branch? He can help if needed

**Comment by scollis** [comment]
Perfect! Thanks @rtanamachi .. some advanced GitHub going on here. Waiting for tests to complete

**Comment by scollis** [comment]
something in Basemap broke in Travis.. re-running CI to see if they fixed it

**Comment by scollis** [comment]
FInally! CI all passed. Merging.. thanks @rtanamachi !!

**Pull request merged**
