### PR TITLE
ADD: `radar_freq` param in `hydroclass_semisupervised`

### PR DESCRIPTION
**Pull request by RBhupi**
- [x] Documentation reflects changes

1. Added `radar_freq` option when frequency information is missing from the radar object.
2. Now always print warning showing frequency used by the function.
3. Added docstring for thechange.
4. Modified the old notes section to include `radar_freq`.

### CODE REVIEW

**Review by mgrover1 — CHANGES_REQUESTED** [review]
@RBhupi - can you please add a test/example here?

**Review by mgrover1 — CHANGES_REQUESTED** [review]
@RBhupi - can you please convert your example to a `.py`? It should look similar to other examples (ex. https://github.com/ARM-DOE/pyart/blob/main/examples/retrieve/plot_column_subset.py). This will ensure it renders correctly on the example gallery!

**Review by zssherman — COMMENTED** [review]
hydrometeor_class_x-band_example.py 
rename file to:
plot_hydrometeor_class_x_band.py

Needed so it is generated correctly.

**Comment by RBhupi** [comment]
This is failing because of the missing file. I want to use this file in my example which I can take from the ARM servers.

**Comment by zssherman** [comment]
@RBhupi If you want to pull the file and run that, you can do a PR adding the file to https://github.com/openradar/open-radar-data

then once the file has been added to the data directory, run python make_registry.py

**Comment by zssherman** [comment]
@RBhupi This looks good to me now!

**Review by zssherman — APPROVED** [review]

**Review by mgrover1 — APPROVED** [review]

**Pull request merged**
