### PR TITLE
ADD: added a function that will make a VAD profile from a radar scan and a unit test to go along with the function

### PR DESCRIPTION
**Pull request by jhemedin**
Function will crate a VAD profile from a given radar scan. Testing of the code was done by comparing it to known profiles from soundings. The following images are examples of output from the code and overlaying it on top of the sounding data to compare it.
vad_sounding_uv_overlay
vad_sounding_uv_overlay_100samples
vad_sounding_uv_overlay_10000samples

### CODE REVIEW

**Comment by zssherman** [comment]
Restarting build now that the cartopy issue is temporarily fixed.

**Comment by scollis** [comment]
@rcjackson can you please grab this branch and do a VAD on a CPOL volume to make sure it runs.

**Comment by rcjackson** [comment]
vad test cpol

Reasonable match between VAD and sounding winds....after a couple of changes it's good to go.

**Comment by zssherman** [comment]
That was my bad. So pretty much the return is:
vad : HorizontalWindProfile
     A wind profile of u wind vwind etc 
     created from a radar object.

Or something along those lines

**Comment by swnesbitt** [comment]
Guessing that the initial tests above were using synthetic data?

**Comment by scollis** [comment]
That's the idea behind the Unit test @swnesbitt ... However @rcjackson comparison is from CPOL and compared to real sounding from Darwin.. So what you see there is both very real and very pleasing.. 
This is a very nice new Py-ART feature.

**Comment by scollis** [comment]
Ok team! Nice work. This has been a great example of an added capability I have wanted for a LONG time. 
Well done.. Merging

**Pull request merged**
