### PR TITLE
ADD: Velocity texture calculation into pyart.filters

### PR DESCRIPTION
**Pull request by rcjackson**
I have added a much faster velocity texture calculation and placed it into a subroutine into pyart.filters that returns a velocity texture field dictionary.

### CODE REVIEW

**Comment by scollis** [comment]
Closing and re-opening to force CI to re-run

**Comment by scollis** [comment]
Thanks @rcjackson !! Checks have passed.. @zssherman Can you confirm pep8?

**Comment by zssherman** [comment]
Went through it, it now is pep8 compliant. I'm not sure @scollis if you want a git squash done on some of the commits, but besides that, it looks good to me.

**Comment by scollis** [comment]
No need for squash.. Once the checks pass I will accept! Thanks all for this very nice contribution!

**Comment by scollis** [comment]
Thanks! All passed.. Merging

**Pull request merged**
