### PR TITLE
Added additional colorbar functionality

### PR DESCRIPTION
**Pull request by HumphreysCarter**
Added additional colorbar functionality from matplotlib, see https://github.com/ARM-DOE/pyart/issues/813.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@HumphreysCarter 

Since those keyword arguments are all fed to matplotlib `colorbar`, why not just use `**kwargs` to propagate this?

**Comment by HumphreysCarter** [comment]
> 
> 
> @HumphreysCarter
> 
> Since those keyword arguments are all fed to matplotlib `colorbar`, why not just use `**kwargs` to propagate this?

That's true, I hadn't had much experience with `**kwargs` so that's probably why I overlooked that.

**Comment by kmuehlbauer** [comment]
In the end that's a design decision. If `**kwargs` are used, the user can specify all kwargs which `plt.colorbar` can consume and has absolute freedom to tweak the colorbar as wanted . You still can give reasonable defaults within this funcion when a specific `kwarg` (eg. `aspect`) is not set. 

@zssherman It seems `plot_colorbar` is just a thin wrapper around `plt.colorbar` with some additions, so it might be a good idea to use `kwargs` here. Thoughts?

**Comment by zssherman** [comment]
Thanks @kmuehlbauer for the feedback, and I do agree! @HumphreysCarter Thank you for the PR! I'm wondering if then we can keep the doc strings as it would help the user navigate the other features if they wish to change, but I do agree the kwargs would allow for more freedom.

**Comment by HumphreysCarter** [comment]
Hi @zssherman sorry for my delay in getting this fixed. I removed the doc strings and followed @kmuehlbauer's recommendation of using kwargs. I believe I implemented them correctly?

**Comment by zssherman** [comment]
@HumphreysCarter No worries! Looks like the error is plt.colorbar got tabbed possibly on accident.

**Comment by HumphreysCarter** [comment]
Whoops! Thanks for pointing that out @zssherman.

**Comment by zssherman** [comment]
No worries!

**Comment by zssherman** [comment]
Thanks @HumphreysCarter for the PR! I'm going to accept and do a test fix in a new PR.

**Comment by HumphreysCarter** [comment]
Awesome, thanks @zssherman!

**Pull request merged**
