### PR TITLE
Add functions of reading and plotting Composite Reflectivity (CRF)

### PR DESCRIPTION
**Pull request by zxdawn**
I wrote functions of reading and plotting Composite Reflectivity (CRF). Please check and give some suggestions :)

### CODE REVIEW

**Comment by scollis** [comment]
Hey @zxdawn I think you accidentally included commit from #744 in this PR

**Comment by zxdawn** [comment]
@scollis Oh, I made a mistake. You can exclude that commit. Waiting for your suggestion.

**Comment by scollis** [comment]
It will be much easier for you to do it.. see: https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-pull-request

**Comment by scollis** [comment]
Thanks @zxdawn .. @zssherman assigned to review

**Comment by zxdawn** [comment]
@scollis Thank you for your tutorial. Revert it now.

**Comment by zssherman** [comment]
I'm going to close this for now.

**Pull request closed without merging**
