### PR TITLE
TST: Fix median filter depreciation warnings as well as more tests for simple moments.

### PR DESCRIPTION
**Pull request by zssherman**

### CODE REVIEW

**Comment by zssherman** [comment]
Some weird behavior going on with arrays matching or not generating the same on mac....

**Comment by mgrover1** [comment]
Looks good now!

**Review by mgrover1 — APPROVED** [review]
Great! Thanks @zssherman

**Comment by zssherman** [comment]
@mgrover1 Did some more changes for the default config and another depreciation warning,

**Pull request merged**
