### PR TITLE
MAINT: Change of graph modules to reflect favoring of Cartopy.

### PR DESCRIPTION
**Pull request by zssherman**
RadarMapDisplay now has cartopy mapping and basemap now is found in radarmapdisplay_basemap if user's still want to use it, but they will get a warning. Updated all unit tests and __init__.py file to reflect changes and also docstrings. GridMapDisplay is now GridMapDisplayBasemap, which will also throw a warning if user has basemap and wants to use. Working on a gridmapdisplay.py module that uses Cartopy. Also removed temporary cartopy fix from pull request #770 because this issue was fixed in Cartopy.

### CODE REVIEW

**Comment by zssherman** [comment]
@rcjackson There is a warning that mentions Cartopy being implemented soon on line 66. Your first point do you mean keep it as GridMapDisplay instead of GridMapDisplayBasemap until a Cartopy version exists?

**Comment by rcjackson** [comment]
> @rcjackson There is a warning that mentions Cartopy being implemented soon on line 66. Your first point do you mean keep it as GridMapDisplay instead of GridMapDisplayBasemap until a Cartopy version exists?

Yeah, I would keep it as GridMapDisplay for now so that nobody's code breaks.

**Comment by scollis** [comment]
Keep GridMapDisplay's behavior.. but add a warning. duplicate GridMapDIsplay in GridMapDisplayBasemap (sans warning)

**Comment by scollis** [comment]
and both basemap based methods will only work when basemap is present

**Comment by zssherman** [comment]
@scollis Rerunning now, saw the gitter.

**Comment by scollis** [comment]
@rcjackson can you comment on changes made

**Comment by rcjackson** [comment]
It's good now.

**Comment by scollis** [comment]
Thanks team! Making great progress. Merging

**Pull request merged**
