### PR TITLE
Fix bug in sign calculation

### PR DESCRIPTION
**Pull request by wave100**
"b0b1000000000000000" ->  "0b1000000000000000"

### CODE REVIEW

**Comment by scollis** [comment]
Thanks @wave100 !! @rcjackson Do you have some level3 data we can test this on? 
All tests have passed and this is a small change so don't spend a huge amount of time.. @jjhelmus as the code's author if you have a view I would appreciate it if you have time to post

**Comment by scollis** [comment]
Thanks @jjhelmus !

**Comment by rcjackson** [comment]
It works on an example level 3 file from KLOT I just downloaded with no issues.

**Comment by scollis** [comment]
Perfect! Thanks @wave100 for the nice bugfixes!

**Pull request merged**
