### PR TITLE
ENH: Update Py-ART to pull colormaps from cmweather

### PR DESCRIPTION
**Pull request by zssherman**
- [ ] Documentation reflects changes

### CODE REVIEW

**Comment by zssherman** [comment]
@mgrover1 It's failing, i'm wondering if the cmweather import needs to be in the main __init__.py so when the pyart config loads the colormaps

**Comment by zssherman** [comment]
@mgrover1 Nvm, i forgot to replace it in the __init__.py

**Review by mgrover1 — CHANGES_REQUESTED** [review]
My only suggestion here would be to add a helpful warning, suggesting that users remove `pyart_` in front of their colormap specification. This will likely have breaking changes once we cut a new release.

**Comment by zssherman** [comment]
@mgrover1 Where do you think we should include the warning at?

**Comment by mgrover1** [comment]
I think within the `pyart/graph/__init__.py` module. One other option here is to create a dedicated Py-ART 2.0 branch, and commit this there, so we can prep for breaking changes. What do you think?

**Comment by zssherman** [comment]
@mgrover1 I think either is fine, I'll let you make the decision on that.

**Comment by mgrover1** [comment]
@zssherman - can you make a PR to the new `release/2.0` branch?
https://github.com/ARM-DOE/pyart/tree/release/2.0

This will ensure that breaking changes go on that branch

**Comment by zssherman** [comment]
@mgrover1 Sounds good! That PR is now open, closing this one.

**Pull request closed without merging**
