### PR TITLE
ENH: Delayed loading of field data from radar files.

### PR DESCRIPTION
**Pull request by jjhelmus**
Add support for delayed loading of field data from radar files in multiple formats.

### CODE REVIEW

**Comment by jjhelmus** [comment]
Some example of the improvements in access time that can be archived by delaying the loading of field data until accessing the 'data' key of the field dictionary when only a single field is to be examined:

### NEXRAD Level II Archive files:

``` Python
In [6]: %timeit radar = pyart.io.read_nexrad_archive('KATX20130717_195021_V06', delay_field_loading=False); radar.fields['reflectivity']['data']
1 loops, best of 3: 1.96 s per loop

In [7]: %timeit radar = pyart.io.read_nexrad_archive('KATX20130717_195021_V06', delay_field_loading=True); radar.fields['reflectivity']['data']
1 loops, best of 3: 943 ms per loop
```

### CfRadial

``` Python
In [8]: %timeit radar = pyart.io.read_cfradial('sgpxsaprrhicmacI5.c0.20110524.015604_NC4.nc', delay_field_loading=False); radar.fields['reflectivity_horizontal']['data']
1 loops, best of 3: 335 ms per loop

In [9]: %timeit radar = pyart.io.read_cfradial('sgpxsaprrhicmacI5.c0.20110524.015604_NC4.nc', delay_field_loading=True); radar.fields['reflectivity_horizontal']['data']
10 loops, best of 3: 57.2 ms per loop
```

Results will vary greatly depending on file content (greater speed ups when the file contains many fields) and hardware especially hard drive speed.  These tests were run on a machine with a non-SSD hard drive.

**Comment by jjhelmus** [comment]
Please do not merge, this is still a work in progress.

**Comment by jjhelmus** [comment]
Checklist of lazy field loading in Py-ART:

## To Support
* [ ] RSL
* [ ] MDV
* [ ] Sigmet
* [ ] CHL
* [X] CfRadial
* [X] NEXRAD Level 2 Archive
* [ ] NEXRAD Level 2 CDM

## No plan to support (add keyword and docs indicating)
* [ ] NEXRAD Level 3

**Comment by jjhelmus** [comment]
Support for delayed field data loading for CHL, NEXRAD Level 2 CDM, NEXRAD Level 3 and Sigmet files is quite involved or yield minimal performance enhancements.  Will leave implementing delayed load of field data from MDV files for @gamaanderson.  Support for other file types can be implemented as needed.

**Comment by gamaanderson** [comment]
I will work on that as soon as this PR is merged, since I need to import lazydict.

**Comment by jjhelmus** [comment]
Sounds good, Travis is taking a bit to run the CI tests, I'll merge once these pass.

**Pull request merged**
