### PR TITLE
ENH: map_gates_to_grid function

### PR DESCRIPTION
**Pull request by jjhelmus**
Full commit history for this enhancement can be found in the jjhelmus/faster_gridding branch.
This branch has been rebased to remove unnecessary intermediate code.

### CODE REVIEW

**Comment by jjhelmus** [comment]
This new gridding routines has similar features to the `map_to_grid` function but is significantly faster and has better scaling performance with increasing grid size and number of radar gates.  Run time should increase linearly with respect to both.

I would like to compare this to the new routines in PR #265 and Issue #182 and to an improved `map_to_grid` which is optimized using Cython see how all four compare in timing and scaling.

**Comment by jjhelmus** [comment]
Some example timing adapted from the [Py-ART examples](http://arm-doe.github.io/pyart/dev/auto_examples/index.html#mapping-examples)

``` Python
import cProfile
import pstats

import numpy as np
import pyart

def do_grid_map_gates_to_grid(radar):
    grids = pyart.map.map_gates_to_grid(
        (radar, ), grid_shape=(1, 241, 241),
        grid_limits=((2000, 12000), (-123000.0, 123000.0),
                    (-123000.0, 123000.0)),
        fields=['reflectivity'],
        weighting_function='BARNES')
    return grids

def do_grid_map_to_grid(radar):
    grids = pyart.map.map_to_grid(
        (radar, ), grid_shape=(1, 241, 241),
        grid_limits=((2000, 12000), (-123000.0, 123000.0),
                    (-123000.0, 123000.0)),
        fields=['reflectivity'],
        weighting_function='BARNES')
    return grids


if __name__ == "__main__":

    RADAR_FILE = '110635.mdv'
    radar = pyart.io.read_mdv(RADAR_FILE)
    radar.fields['reflectivity']['data'][:, -10:] = np.ma.masked

    cProfile.run('grids = do_grid_map_to_grid(radar)', 'old.prof')
    s = pstats.Stats('old.prof')
    s.strip_dirs().sort_stats('time').print_stats(20)

    cProfile.run('grids = do_grid_map_gates_to_grid(radar)', 'new.prof')
    s = pstats.Stats('new.prof')
    s.strip_dirs().sort_stats('time').print_stats(20)
```

Results

```
Thu May 14 14:38:40 2015    old.prof

         5996729 function calls in 16.713 seconds

   Ordered by: internal time
   List reduced from 90 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    43309    2.156    0.000    3.413    0.000 core.py:3033(__getitem__)
    58081    2.068    0.000    2.333    0.000 {method 'query_ball_point' of 'pyart.map.ckdtree.cKDTree' objects}
        1    1.750    1.750   16.664   16.664 grid_mapper.py:274(map_to_grid)
    58081    1.343    0.000    5.270    0.000 grid_mapper.py:242(find_neighbors_and_dists)
    58081    1.037    0.000    1.197    0.000 grid_mapper.py:775(roi)
   129927    0.934    0.000    0.934    0.000 {method 'reduce' of 'numpy.ufunc' objects}
        1    0.691    0.691    0.691    0.691 common.py:61(radar_coords_to_cart)
    86625    0.671    0.000    1.674    0.000 core.py:2788(__array_finalize__)
   129938    0.605    0.000    1.235    0.000 core.py:2763(_update_from)
  1385979    0.594    0.000    0.594    0.000 {getattr}
    43307    0.557    0.000    1.213    0.000 kdtree.py:15(minkowski_distance_p)
   505940    0.540    0.000    0.540    0.000 {numpy.core.multiarray.array}
    58082    0.376    0.000    0.425    0.000 core.py:3078(__setitem__)
    43307    0.323    0.000    3.043    0.000 extras.py:996(dot)
        1    0.288    0.288    0.395    0.395 grid_mapper.py:232(__init__)
    43307    0.271    0.000    1.300    0.000 core.py:2638(__new__)
   751056    0.209    0.000    0.209    0.000 {isinstance}
    43307    0.201    0.000    1.585    0.000 kdtree.py:48(minkowski_distance)
   606371    0.189    0.000    0.189    0.000 {method 'update' of 'dict' objects}
    58081    0.160    0.000    0.160    0.000 {min}


Thu May 14 14:38:42 2015    new.prof

         313 function calls in 2.188 seconds

   Ordered by: internal time
   List reduced from 71 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    2.180    2.180    2.180    2.180 {method 'map_gates_to_grid' of 'pyart.map._gate_to_grid_map.GateToGridMapper' objects}
        1    0.006    0.006    2.188    2.188 gates_to_grid.py:28(map_gates_to_grid)
        1    0.001    0.001    0.001    0.001 {method 'find_roi_for_grid' of 'pyart.map._gate_to_grid_map.GateToGridMapper' objects}
        1    0.000    0.000    0.000    0.000 core.py:1072(__call__)
        1    0.000    0.000    0.000    0.000 core.py:782(__call__)
        6    0.000    0.000    0.000    0.000 core.py:2788(__array_finalize__)
        1    0.000    0.000    0.000    0.000 core.py:925(__call__)
        2    0.000    0.000    0.000    0.000 {numpy.core.multiarray.zeros}
        9    0.000    0.000    0.000    0.000 core.py:2763(_update_from)
        9    0.000    0.000    0.000    0.000 {numpy.core.multiarray.array}
       85    0.000    0.000    0.000    0.000 {getattr}
        5    0.000    0.000    0.000    0.000 core.py:621(getdata)
        1    0.000    0.000    0.000    0.000 {numpy.core.multiarray.copyto}
        1    0.000    0.000    0.000    0.000 gates_to_grid.py:211(_parse_roi_func)
        3    0.000    0.000    0.000    0.000 {method 'astype' of 'numpy.ndarray' objects}
        1    0.000    0.000    0.000    0.000 {method 'reduce' of 'numpy.ufunc' objects}
        1    0.000    0.000    2.188    2.188 profile_one_radar.py:7(do_grid_map_gates_to_grid)
        1    0.000    0.000    0.000    0.000 common.py:55(ax_radius)
       42    0.000    0.000    0.000    0.000 {method 'update' of 'dict' objects}
        2    0.000    0.000    0.000    0.000 core.py:3033(__getitem__)
```

If you change the weighting_function to "CRESSMAN" in both cases the profiles are 35.3 seconds vs. 1.8 seconds.

**Comment by jjhelmus** [comment]
``` Python
import cProfile
import pstats
import pyart

def do_grid_new(radar_se, radar_sw):
    return pyart.map.map_gates_to_grid(
        (radar_se, radar_sw),
        grid_shape=(1, 201, 201),
        grid_limits=((1000, 1000), (-50000, 40000), (-60000, 40000)),
        grid_origin = (36.57861, -97.363611),
        fields=['corrected_reflectivity_horizontal'],
        refl_field='corrected_reflectivity_horizontal',
        max_refl=100.)

def do_grid_old(radar_se, radar_sw):
    return pyart.map.map_to_grid(
        (radar_se, radar_sw),
        grid_shape=(1, 201, 201),
        grid_limits=((1000, 1000), (-50000, 40000), (-60000, 40000)),
        grid_origin = (36.57861, -97.363611),
        fields=['corrected_reflectivity_horizontal'],
        refl_field='corrected_reflectivity_horizontal',
        max_refl=100.)

if __name__ == "__main__":

    XSAPR_SW_FILE = 'swx_20120520_0641.nc'
    XSAPR_SE_FILE = 'sex_20120520_0641.nc'
    radar_sw = pyart.io.read_cfradial(XSAPR_SW_FILE)
    radar_se = pyart.io.read_cfradial(XSAPR_SE_FILE)

    cProfile.run('grids = do_grid_old(radar_se, radar_sw)', 'old.prof')
    s = pstats.Stats('old.prof')
    s.strip_dirs().sort_stats('time').print_stats(20)

    cProfile.run('grids = do_grid_new(radar_se, radar_sw)', 'new.prof')
    s = pstats.Stats('new.prof')
    s.strip_dirs().sort_stats('time').print_stats(20)
```

Results

```
Thu May 14 14:44:38 2015    old.prof

         4393821 function calls in 20.164 seconds

   Ordered by: internal time
   List reduced from 89 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    32021    3.282    0.000    4.257    0.000 core.py:3033(__getitem__)
    40401    2.563    0.000    2.760    0.000 {method 'query_ball_point' of 'pyart.map.ckdtree.cKDTree' objects}
        1    2.391    2.391   20.084   20.084 grid_mapper.py:274(map_to_grid)
    40401    1.937    0.000    6.350    0.000 grid_mapper.py:242(find_neighbors_and_dists)
        2    1.792    0.896    1.792    0.896 common.py:61(radar_coords_to_cart)
    96070    1.145    0.000    1.145    0.000 {method 'reduce' of 'numpy.ufunc' objects}
        1    0.835    0.835    1.082    1.082 grid_mapper.py:232(__init__)
    40401    0.783    0.000    0.914    0.000 grid_mapper.py:775(roi)
    32019    0.573    0.000    1.311    0.000 kdtree.py:15(minkowski_distance_p)
    64064    0.522    0.000    1.288    0.000 core.py:2788(__array_finalize__)
    96097    0.456    0.000    0.933    0.000 core.py:2763(_update_from)
  1024981    0.455    0.000    0.455    0.000 {getattr}
   368998    0.425    0.000    0.425    0.000 {numpy.core.multiarray.array}
    40403    0.302    0.000    0.340    0.000 core.py:3078(__setitem__)
    32019    0.265    0.000    2.383    0.000 extras.py:996(dot)
    32019    0.210    0.000    0.992    0.000 core.py:2638(__new__)
    32019    0.193    0.000    1.646    0.000 kdtree.py:48(minkowski_distance)
   552859    0.173    0.000    0.173    0.000 {isinstance}
        4    0.155    0.039    0.196    0.049 function_base.py:3285(meshgrid)
   448432    0.140    0.000    0.140    0.000 {method 'update' of 'dict' objects}


Thu May 14 14:44:43 2015    new.prof

         325 function calls in 4.596 seconds

   Ordered by: internal time
   List reduced from 70 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        2    4.582    2.291    4.582    2.291 {method 'map_gates_to_grid' of 'pyart.map._gate_to_grid_map.GateToGridMapper' objects}
        1    0.012    0.012    4.596    4.596 gates_to_grid.py:28(map_gates_to_grid)
        1    0.001    0.001    0.001    0.001 {method 'find_roi_for_grid' of 'pyart.map._gate_to_grid_map.GateToGridMapper' objects}
        1    0.000    0.000    0.000    0.000 core.py:1072(__call__)
        1    0.000    0.000    0.000    0.000 core.py:782(__call__)
        6    0.000    0.000    0.000    0.000 {method 'astype' of 'numpy.ndarray' objects}
        9    0.000    0.000    0.000    0.000 core.py:2763(_update_from)
        6    0.000    0.000    0.000    0.000 core.py:2788(__array_finalize__)
        1    0.000    0.000    0.000    0.000 core.py:925(__call__)
       86    0.000    0.000    0.000    0.000 {getattr}
        2    0.000    0.000    0.000    0.000 {numpy.core.multiarray.zeros}
        9    0.000    0.000    0.000    0.000 {numpy.core.multiarray.array}
        6    0.000    0.000    0.000    0.000 core.py:621(getdata)
        5    0.000    0.000    0.000    0.000 {numpy.core.multiarray.empty}
        2    0.000    0.000    0.000    0.000 common.py:55(ax_radius)
        1    0.000    0.000    0.000    0.000 gates_to_grid.py:211(_parse_roi_func)
        1    0.000    0.000    0.000    0.000 {numpy.core.multiarray.copyto}
        2    0.000    0.000    0.000    0.000 core.py:595(get_masked_subclass)
        1    0.000    0.000    4.596    4.596 profile_two_radars.py:5(do_grid_new)
        1    0.000    0.000    0.000    0.000 {method 'reduce' of 'numpy.ufunc' objects}
```

Changing the grid size to 21, 201, 201 and the z grid limit to 1000, 21000 the timings are:
`map_to_grid`: 218 sec (x11)
`map_gates_to_grid`: 14.43 (x3.2)

**Comment by scollis** [comment]
Hey @jjhelmus are you returning a grid object or just the dictionary?

**Comment by jjhelmus** [comment]
Just a dictionary, use [`pyart.map.grid_from_radars`](http://arm-doe.github.io/pyart-docs-travis/user_reference/generated/pyart.map.grid_from_radars.html) with gridding_algo="map_gates_to_grid" to create a **Grid** object.

**Comment by scollis** [comment]
Awesome
Initial testing very impressive


On 5/14/15 3:51 PM, Jonathan J. Helmus wrote:
>
> Just a dictionary, use |pyart.map.grid_from_radars| 
> <http://arm-doe.github.io/pyart-docs-travis/user_reference/generated/pyart.map.grid_from_radars.html> 
> with gridding_algo="map_gates_to_grid" to create a *Grid* object.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ARM-DOE/pyart/pull/290#issuecomment-102165546>.
>

-- 
I ride for Parkinsons research http://www.events.org/sponsorship.aspx?id=51573

**Comment by gamaanderson** [comment]
Great work @jjhelmus this will be very useful. I got 1 million points grid (with 26 fields) in 26s. This is pretty close to what we need, parallel processing should do the rest.
As I have experience myself how small alteration in cython can have severe consequences, I have to ask, how are you filling? do you think cython can be further improved, or this is it?

The method in PR #265 did the same test in 2.6s, but it does not parallelize very well. 
Nevertheless, as for me, this new method remove the necessity of this PR. I would just ask to let gridding_algo accept also functions, like roi_func does. That being done, you may, if you want, close PR #265 without merging.

**Comment by jjhelmus** [comment]
Thanks!  The Cython in the _gate_to_grid_map.pyx file  is quite optimized, I don't expect that it can be improved much. Nearly all the computational time is spent in the `map_gates_to_grid` and `map_gate` methods which are almost complete typed and generating pure C code.

 A good method for finding places to improve Cython code is to look at the annotated html file generated by the command `cython -a _gate_to_grid_map.pyx`. Line highlighted in yellow are good candidates where adding type information may result in speed increases.  As can be see for the [_gate_to_grid_map.html](https://cdn.rawgit.com/jjhelmus/ff5ced43b1d0d1433efe/raw/00c57f0129996287fc07480b773fe68d3d80f1ce/_gate_to_grid_map.html) the entirety of `map_gate` method is free of yellow as is most of the `map_gates_to_grid`.

You may be interested in a talk I gave recently on optimizing Python and Cython code, slides and a video of the talk are available on the [conference website](https://sea.ucar.edu/event/profiling-python-code-improve-memory-usage-and-execution-time).  I'll be giving another presentation on Cython at the end of the month at [DePy](http://mdp.cdm.depaul.edu/DePy2015/default/schedule).  I'll post the slides and links from that presentation in my [posters repo](https://github.com/jjhelmus/posters)

**Comment by jjhelmus** [comment]
I'll probably still look into merging PR #265, having another gridding algorithm, especially one that is fast is always a good thing.  I'll implement functionality to allow the **gridding_algo** parameter to take a callable function (or class).

**Comment by jjhelmus** [comment]
One final comment.  For multiprocessing [lines 94-120 in gates_to_grid.py](https://github.com/ARM-DOE/pyart/blob/d55b85e70c59e7566f9e6ecb5e826545d5f0c69d/pyart/map/gates_to_grid.py#L94-L120) can be executed in parallel with one radar, sweep, or chunk per process.  The grid_sum and grid_wsum for each chunk would need to be added together to calculate the global averaging.  This requires more memory to store multiple copies of grid_sum and grid_wsum, but would give enhanced performance.

**Comment by gamaanderson** [comment]
Thanks @jjhelmus for all comments, I will take a good look in it all, as I'm personally interested in cython. I will also be testing the new routine, I will let you know of any important results. 

I know PR #265 is some what improvised,  you may want to change the names and how it's structured. If you want just leave comments there and I will make any changes needed, more generic comments on good practices are also appreciated. As I said somewhere before, the code is lacking some readability, but I was not able to improve that without performance lost.

**Comment by gamaanderson** [comment]
@jjhelmus could you test using this version of [_gate_to_grid_map.pyx](https://github.com/simepar/pyart/blob/master/pyart/map/_gate_to_grid_map.pyx). It is faster by one third (from 29s to 19s). The problem is that looking at the C code I can't find the reason for such big difference, the code it is replacing is already optimal.

**Comment by gamaanderson** [comment]
forget about that, I've made something wrong

**Comment by jjhelmus** [comment]
I believe most of the speed up you were seeing was from change in the **RoIFunction** object. I found a similar speed up using the **DistRoI** class.

**Comment by jjhelmus** [comment]
Also a few good papers on books on good programming practices that I would recommend.

* [Best Practices for Scientific Computing](http://arxiv.org/abs/1210.0530) : Free article on good practices
* [The Pragmatic Programmer](http://www.amazon.com/The-Pragmatic-Programmer-Journeyman-Master/dp/020161622X)
* [Clean Code : A Handbook of Agile Software Craftsmanship](http://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882/ref=pd_bxgy_14_img_y)
* [Code Complete: A Practical Handbook of Software Construction](http://www.amazon.com/Code-Complete-Practical-Handbook-Construction/dp/0735619670/ref=pd_bxgy_14_img_z).

[Coding Horror](http://blog.codinghorror.com/) and [Joel on Software](http://www.joelonsoftware.com/) blogs are good reads with some good suggestions.

**Comment by gamaanderson** [comment]
In fact, optimization is so good that most of the time is expend in [here](https://github.com/ARM-DOE/pyart/blob/master/pyart/map/_gate_to_grid_map.pyx#L365-L381), and this is really sensitive to roi size. The only improvement I could find would be to add the following [here](https://github.com/ARM-DOE/pyart/blob/master/pyart/map/_gate_to_grid_map.pyx#L334)

        cdef int flag = 0

        for i in range(self.nfields):
            if not masks[i]:
                flag = 1

        if flag == 0:
            return 0

to avoid executing that part of the code if not needed, this however is just useful in some cases and if `filter_flag=False`

**Pull request merged**
