### PR TITLE
TST: Switch from Nose to Pytest, NOTE: This still needs some work, needed CI to run.

### PR DESCRIPTION
**Pull request by zssherman**
I submitted this pull request to see how appveyor and travis run. More changes will most likely be needed.

Changes the CI, environment files and pyart files to work with pytest. Yield test are now pytest.mark.parametrize, assert_raises and assert_warns are pytest.raise pytest.warns respectively, did multiple pep8 changes to the unit test.

### CODE REVIEW

**Comment by zssherman** [comment]
@scollis The tests pass. DOC build still happens in python 2.7, and in python 2.7 the util directory is ignored because for 2.7, the unit tests fail do to a folder being named tests within the submodule directory. Appveyor has been updated to run pytest. The README, contributors guide, etc have been updated for pytest. All tests that had yields, pretty much tests that needed to be run multiple times based on a list, have been changed to pytest. I ran pylint on every file I changed too, so I did pep8 changes when needed and found a couple of tests that were exact duplicates, so removed them.

I will add the pytest pep8 checker, etc another time. Wanted to get pytest running first before any of the fancy stuff.

**Comment by scollis** [comment]
So are we good to accept this PR?

**Comment by scollis** [comment]
@rcjackson can you please download and run the tests.

**Comment by zssherman** [comment]
@scollis I'd say so, but being 50 files that have been changed, might need a review, and just saw you assigned Bobby, so beat me to it.

**Comment by scollis** [comment]
Ok.. Thanks for the review @rcjackson Merging.

**Pull request merged**
